INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME)  VALUES ('1', 'India');
INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME)  VALUES ('2', 'USA');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('1', '1', 'Telangana');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('2', '1', 'Ap');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('3', '2', 'Colorado');
INSERT INTO KEYSKILLS ( ID, SKILL ) VALUES ( 1, 'java');
INSERT INTO KEYSKILLS ( ID, SKILL ) VALUES ( 2, '.net');
insert into hibernate_sequences(sequence_name, sequence_next_hi_value) values('user', 0);
update hibernate_sequences set sequence_next_hi_value = 1 where sequence_next_hi_value = 0 and sequence_name = 'user';
insert into user (account_type, email_id, first_name, last_name, password, title, userstatus,IS_AGREED_TC,USER_NAME, id) values ('ADMIN', 'sri3', 'sri', 'ch', 's', 'MR', 'Active',1,'a', 1);
insert into admin (designation, profile_pic, id) values ('it', NULL, 1);
update hibernate_sequences set sequence_next_hi_value = 2 where sequence_next_hi_value = 1 and sequence_name = 'user';
insert into user (account_type, email_id, first_name, last_name,  password, title, userstatus,IS_AGREED_TC,USER_NAME, id) values ('REVIEWER', 'sri4', 'ch', 'sri', 's', 'MR', 'Active',1,'b', 32768);
insert into admin (designation, profile_pic, id) values ('it', NULL, 32768);
insert into stock_exchange(name) values('Bombay Stock Exchange');
insert into stock_exchange(name) values('National Stock Exchange');
insert into stock_exchange(name) values('Shenzhen Stock Exchange');
insert into stock_exchange(name) values('Shanghai Stock Exchange');
insert into stock_exchange(name) values('London Stock Exchange');
insert into stock_exchange(name) values('SIX Swiss Exchange');
insert into stock_exchange(name) values('NASDAQ Stock Exchange');
insert into stock_exchange(name) values('Osaka Securities Exchange');
insert into stock_exchange(name) values('JASDAQ Securities Exchange');
insert into stock_exchange(name) values('Hercules Stock Exchange');
insert into stock_exchange(name) values('Tokyo Stock Exchange');
insert into stock_exchange(name) values('Berlin Stock Exchange');
insert into stock_exchange(name) values('Frankfurt Stock Exchange');
insert into stock_exchange(name) values('Borsa Italiana');
insert into stock_exchange(name) values('Italian Stock Exchange');
insert into stock_exchange(name) values('Hong Kong Stock Exchange');
insert into stock_exchange(name) values('Korea Stock Exchange');
insert into stock_exchange(name) values('Toronto Stock Exchange');
insert into stock_exchange(name) values('TSX Venture Exchange');
insert into stock_exchange(name) values('Ghana Stock Exchange');
insert into stock_exchange(name) values('Nairobi Stock Exchange');
insert into stock_exchange(name) values('Nigerian Stock Exchange');
insert into stock_exchange(name) values('JSE Securities Exchange');
insert into stock_exchange(name) values('Zimbabwe Stock Exchange');
insert into stock_exchange(name) values('Australian Securities Exchange');
insert into stock_exchange(name) values('Dhaka Stock Exchange');
insert into stock_exchange(name) values('Indonesia Stock Exchange');
insert into stock_exchange(name) values('Malaysia Exchange');
insert into stock_exchange(name) values('Karachi Stock Exchange');
insert into stock_exchange(name) values('Philippine Stock Exchange');
insert into stock_exchange(name) values('Singapore Exchange');
insert into stock_exchange(name) values('Colombo Stock Exchange');
insert into stock_exchange(name) values('Taiwan Stock Exchange');
insert into stock_exchange(name) values('Stock Exchange of Thailand');
insert into stock_exchange(name) values('Euronext - Brussels');
insert into stock_exchange(name) values('Bulgarian Stock Exchange');
insert into stock_exchange(name) values('Zagreb Stock Exchange');
insert into stock_exchange(name) values('Cyprus Stock Exchange');
insert into stock_exchange(name) values('Euronext - Paris');
insert into stock_exchange(name) values('Athens Stock Exchange');
insert into stock_exchange(name) values('Irish Stock Exchange');
insert into stock_exchange(name) values('Luxembourg Stock Exchange');
insert into stock_exchange(name) values('Oslo Stock Exchange');
insert into stock_exchange(name) values('Warsaw Stock Exchange');
insert into stock_exchange(name) values('Euronext - Lisbon');
insert into stock_exchange(name) values('Russian Stock Exchange');
insert into stock_exchange(name) values('Istanbul Stock Exchange');
insert into stock_exchange(name) values('Egyptian Stock Exchange');
insert into stock_exchange(name) values('Tel Aviv Stock Exchange');
insert into hibernate_sequences(sequence_name, sequence_next_hi_value) values('report', 0);

update hibernate_sequences set sequence_next_hi_value = 3 where sequence_next_hi_value = 2 and sequence_name = 'user';
insert into user (account_type, is_agreed_tc, email_id, first_name, last_name, password, title, user_name, userstatus, id) values ('AUTHOR', 1, 'kumar@gmail.com', 'Anilkumar ', 'Ravula', 'pirate', 'MR', 'anil', 'Active', 65536);
insert into author (bio, city, country, mobile, id) values ('asdasdasdasds', 'hello', '1', '9505485048', 65536);
insert into author_key_skill (author_id, skill_id) values (65536, 2);

insert into user (account_type, email_id, first_name, last_name,  password, title, userstatus,IS_AGREED_TC,USER_NAME, id) values ('PUBLISHER', 'anil1@gamil.com', 'anil', 'sri', 'pirate', 'MR', 'Active',1,'anil', 32769);


insert into report_assigners (publisher_id, report_id, reviwer_id, report_assigners_id,active) values (32769, 1, 32768, 1,'Y');
insert into report_assigners (publisher_id, report_id, reviwer_id, report_assigners_id,active) values (32769, 2, 32768, 2,'Y');


INSERT INTO REPORT_CYCLE (STATUS_ID, STATUS_NAME)  VALUES ('1', 'CREATED');
INSERT INTO REPORT_CYCLE (STATUS_ID, STATUS_NAME)  VALUES ('2', 'REVIWER PENDING');
INSERT INTO REPORT_CYCLE (STATUS_ID, STATUS_NAME)  VALUES ('3', 'REVIWER COMMENTS');
INSERT INTO REPORT_CYCLE (STATUS_ID, STATUS_NAME)  VALUES ('4', 'PUBLISHED');

insert into user (account_type, email_id, first_name, last_name,  password, title, userstatus,IS_AGREED_TC,USER_NAME, id) values ('PUBLISHER', 'ani', 'ch', 'an', 'ani', 'MR', 'Active',1,'b', 32770);
