INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME)  VALUES ('1', 'India');
INSERT INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME)  VALUES ('2', 'USA');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('1', '1', 'Telangana');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('2', '1', 'Ap');
INSERT INTO STATE ( STATE_ID, COUNTRY_ID, STATE_NAME ) VALUES ('3', '2', 'Colorado');
INSERT INTO KEYSKILLS ( ID, SKILL ) VALUES ( 1, 'java');
INSERT INTO KEYSKILLS ( ID, SKILL ) VALUES ( 2, '.net');




