package com.marketing.tool.domain;
// Generated Apr 20, 2016 11:32:22 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MasterIndustries generated by hbm2java
 */
@Entity
@Table(name = "master_industries")
public class MasterIndustries implements java.io.Serializable {

	@Id
	@Column(name = "mi_id", unique = true, nullable = false)
	private int id;
	
	@Column(name = "mi_indus_name", length = 100)
	private String text;
	
	@Column(name = "mi_indus_icon", length = 100)
	private String icon;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mi_parent_id")
	private MasterIndustries masterIndustries;
	
	@Column(name = "mi_child_id")
	private Integer miChildId;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mi_upd_ts", length = 19)
	private Date miUpdTs;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "masterIndustries")
	private Set<MasterIndustries> children = new HashSet<MasterIndustries>(0);

	public MasterIndustries() {
	}

	public MasterIndustries(int miId) {
		this.id = miId;
	}

	public MasterIndustries(int miId, MasterIndustries masterIndustries, String miIndusName, Integer miChildId,
			Date miUpdTs, Set<MasterIndustries> masterIndustrieses) {
		this.id = miId;
		this.masterIndustries = masterIndustries;
		this.text = miIndusName;
		this.miChildId = miChildId;
		this.miUpdTs = miUpdTs;
		this.children = masterIndustrieses;
	}



	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
	
	public MasterIndustries getMasterIndustries() {
		return masterIndustries;
	}

	public void setMasterIndustries(MasterIndustries masterIndustries) {
		this.masterIndustries = masterIndustries;
	}

	public Integer getMiChildId() {
		return miChildId;
	}

	public void setMiChildId(Integer miChildId) {
		this.miChildId = miChildId;
	}

	public Date getMiUpdTs() {
		return miUpdTs;
	}

	public void setMiUpdTs(Date miUpdTs) {
		this.miUpdTs = miUpdTs;
	}

	public Set<MasterIndustries> getChildren() {
		return children;
	}

	public void setChildren(Set<MasterIndustries> children) {
		this.children = children;
	}

}
