package com.marketing.tool.domain;

// Generated Apr 20, 2016 11:32:22 PM by Hibernate Tools 4.3.1.Final

/**
 * MasterIndustries generated by hbm2java
 */
public class MasterIndustriesView extends MasterIndustries implements java.io.Serializable {

	private SelectedState state=new SelectedState();

	public SelectedState getState() {
		return state;
	}

	public void setState(SelectedState state) {
		this.state = state;
	}


	class SelectedState {
		private boolean opened=false;
		private boolean disabled=false;
		private boolean selected=false;
		public boolean isOpened() {
			return opened;
		}
		public void setOpened(boolean opened) {
			this.opened = opened;
		}
		public boolean isDisabled() {
			return disabled;
		}
		public void setDisabled(boolean disabled) {
			this.disabled = disabled;
		}
		public boolean isSelected() {
			return selected;
		}
		public void setSelected(boolean selected) {
			this.selected = selected;
		}
				
	}

}
